package com.questadb;
import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.concurrent.*;import io.github.muntashirakon.adb.AdbStream;
public class MainActivity extends Activity{
 LinearLayout root; EditText host,port,code,command; TextView status,log; ExecutorService io=Executors.newSingleThreadExecutor(); AdbConnectionManager manager; int accent=Color.rgb(102,224,194);
 TextView tv(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.WHITE);t.setPadding(18,8,18,8);return t;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(18);b.setAllCaps(false);return b;} EditText f(String h){EditText e=new EditText(this);e.setHint(h);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.LTGRAY);e.setSingleLine();return e;}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);ui();}
 void ui(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,15,20,15);root.setBackgroundColor(Color.rgb(11,15,20));TextView t=tv("QUEST ADB",30);t.setTextColor(accent);root.addView(t);status=tv("Not connected",17);root.addView(status);
  LinearLayout c=new LinearLayout(this);host=f("Quest IP");port=f("Pair/ADB port");code=f("6-digit pairing code");code.setInputType(2);port.setText("37123");c.addView(host,new LinearLayout.LayoutParams(0,65,2));c.addView(port,new LinearLayout.LayoutParams(0,65,1));c.addView(code,new LinearLayout.LayoutParams(0,65,1));root.addView(c);
  LinearLayout a=new LinearLayout(this);Button p=btn("PAIR");Button con=btn("CONNECT");a.addView(p,new LinearLayout.LayoutParams(0,70,1));a.addView(con,new LinearLayout.LayoutParams(0,70,1));root.addView(a);TextView ft=tv("VR FEATURES",22);ft.setTextColor(accent);root.addView(ft);
  LinearLayout g=new LinearLayout(this);String[] fs={"Platforms","Flying","Tag Aura","Tag Gun","Kick Gun","Speed"};for(String x:fs){Switch s=new Switch(this);s.setText(x);s.setTextColor(Color.WHITE);s.setTextSize(15);g.addView(s,new LinearLayout.LayoutParams(0,65,1));}root.addView(g);TextView st=tv("ADB SHELL",22);st.setTextColor(accent);root.addView(st);LinearLayout sh=new LinearLayout(this);command=f("ADB shell command");Button run=btn("RUN");sh.addView(command,new LinearLayout.LayoutParams(0,65,4));sh.addView(run,new LinearLayout.LayoutParams(0,65,1));root.addView(sh);log=tv("Ready. Pair your Quest using Wireless Debugging.",14);ScrollView sv=new ScrollView(this);sv.addView(log);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);p.setOnClickListener(v->pair());con.setOnClickListener(v->connect());run.setOnClickListener(v->shell());}
 void add(String s){runOnUiThread(()->log.setText(log.getText()+"\n"+s));}int port(){try{return Integer.parseInt(this.port.getText().toString().trim());}catch(Exception e){return -1;}}void init(){try{if(manager==null)manager=AdbConnectionManager.getInstance(this);}catch(Exception e){add("Setup error: "+e.getMessage());}}
 void pair(){String h=host.getText().toString().trim(),c=code.getText().toString().trim();if(port()<1||c.length()!=6){add("Enter Quest IP, pairing port, and 6-digit code.");return;}init();io.execute(()->{try{add("Pairing...");boolean ok=manager.pair(h,port(),c);add(ok?"PAIR SUCCESS":"PAIR FAILED");}catch(Exception e){add("PAIR ERROR: "+e.getMessage());}});}
 void connect(){String h=host.getText().toString().trim();if(port()<1){add("Enter an ADB port.");return;}init();io.execute(()->{try{add("Connecting...");boolean ok=manager.connect(h,port());add(ok?"CONNECTED":"NOT CONNECTED");runOnUiThread(()->status.setText(ok?"Connected to "+h+":"+port():"Connection failed"));}catch(Exception e){add("CONNECT ERROR: "+e.getMessage());}});}
 void shell(){String cmd=command.getText().toString().trim();if(cmd.isEmpty())return;init();io.execute(()->{try{AdbStream s=manager.openStream("shell:"+cmd);java.io.InputStream in=s.openInputStream();byte[] b=new byte[4096];int n=in.read(b);add("$ "+cmd+"\n"+(n>0?new String(b,0,n):"(no output)"));s.close();}catch(Exception e){add("SHELL ERROR: "+e.getMessage());}});}
 protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
